dist: xenial
language: python
matrix:
    include:
        - python: 3.7
          env: TOXENV=flake8
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - arch: arm64
          python: 3.7
          env: TOXENV=py37
        - arch: arm64
          python: 3.8
          env: TOXENV=py38
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.7
          env: TOXENV=docs
install:
  - pip install tox 
script:
  - tox
